import type { maps } from "./core/map.js";
import { makeChunkMeshRaw } from "./geometry/mesher.js";

export function exportToObj(map: maps.Map): string {
  const vertexMap: { [key: string]: number } = {};
  const uvMap: { [key: string]: number } = {};
  let vertexList: { x: number; y: number; z: number }[] = [];
  let uvList: { x: number; y: number }[] = [];
  let faceList: [number, number, number, number, number, number][] = [];
  let vN = 0;
  let vtN = 0;

  for (let x = 0; x < 16; x++) {
    for (let y = 0; y < 16; y++) {
      for (let z = 0; z < 16; z++) {
        const ch = map.layers[0]!.getAt(x, y, z);
        if (ch) {
          const { vertices, uvs } = makeChunkMeshRaw(ch, {
            xm: map.layers[0]!.getAt(x - 1, y, z) || undefined,
            xp: map.layers[0]!.getAt(x + 1, y, z) || undefined,
            zm: map.layers[0]!.getAt(x, y, z - 1) || undefined,
            zp: map.layers[0]!.getAt(x, y, z + 1) || undefined,
            yp: map.layers[0]!.getAt(x, y - 1, z) || undefined,
            ym: map.layers[0]!.getAt(x, y + 1, z) || undefined,
          });

          for (let i = 0; i < vertices.length; i += 9) {
            let faceData: [number, number, number, number, number, number] = [
              0, 0, 0, 0, 0, 0,
            ];
            for (let j = 0; j < 9; j += 3) {
              const vx = vertices[i + j]! + x * 16;
              const vy = vertices[i + j + 1]! + y * 16;
              const vz = vertices[i + j + 2]! + z * 16;
              const key = `${vx};${vy};${vz}`;
              let idx = vertexMap[key];
              if (!idx) {
                idx = ++vN;
                vertexMap[key] = idx;
                vertexList.push({ x: vx, y: vy, z: vz });
              }
              faceData[j / 3] = idx;

              const tx = uvs[((i + j) / 3) * 2]!;
              const ty = uvs[((i + j) / 3) * 2 + 1]!;
              const keyT = `${tx};${ty}`;
              let idxT = uvMap[keyT];
              if (!idxT) {
                idxT = ++vtN;
                uvMap[keyT] = idxT;
                uvList.push({ x: tx, y: ty });
              }
              faceData[j / 3 + 3] = idxT;
            }
            faceList.push(faceData);
          }
        }
      }
    }
  }

  let output = `# Generated by APME / https://github.com/jane-alea/APME\no ${map.name}\n`;
  for (const { x, y, z } of vertexList) {
    output += `  v ${x} ${y} ${z}\n`;
  }

  for (const { x, y } of uvList) {
    output += `  vt ${x} ${y}\n`;
  }

  for (const f of faceList) {
    output += `  f ${f[0]}/${f[3]} ${f[1]}/${f[4]} ${f[2]}/${f[5]}\n`;
  }

  return output;
}
